name: GitHub Page Deploy

on:
  push:
    branches:
      - develop02
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
         submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          # extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy Hugo to gh-pages02
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages02
          publish_dir: ./public
